CREATE DATABASE BOOTSTRAP

use BOOTSTRAP

CREATE TABLE Users
(
	ID INT PRIMARY KEY IDENTITY (1,1),
	FullName VARCHAR(100),
	Email VARCHAR(100),
	Username VARCHAR(100),
	Password VARCHAR(100),
	ConfirmPassword VARCHAR(100)
)

SELECT * FROM Users